CREATE TABLE IF NOT EXISTS objects (
	id TEXT PRIMARY KEY,
	key TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	content_type TEXT NOT NULL DEFAULT '',
	size BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS uploads (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	content_type TEXT NOT NULL DEFAULT '',
	object_id TEXT
);
